package com.virtualdoctor.virtual_doctor.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import com.virtualdoctor.virtual_doctor.model.Session;
import com.virtualdoctor.virtual_doctor.model.User;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;

@Service
public class ReportService {

    public byte[] generateReportPdf(Session session, User user) {
        try {
            Document document = new Document(PageSize.A4, 50, 50, 50, 50);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter.getInstance(document, out);

            document.open();

            Font titleFont = new Font(Font.HELVETICA, 20, Font.BOLD, new Color(10, 22, 40));
            Font sectionFont = new Font(Font.HELVETICA, 13, Font.BOLD, new Color(10, 22, 40));
            Font labelFont = new Font(Font.HELVETICA, 11, Font.BOLD, Color.DARK_GRAY);
            Font valueFont = new Font(Font.HELVETICA, 11, Font.NORMAL, Color.BLACK);
            Font disclaimerFont = new Font(Font.HELVETICA, 9, Font.ITALIC, Color.GRAY);

            // Title
            Paragraph title = new Paragraph("MediAI Consultation Report", titleFont);
            title.setSpacingAfter(4);
            document.add(title);

            Paragraph subtitle = new Paragraph("AI-Powered Virtual Doctor",
                    new Font(Font.HELVETICA, 11, Font.NORMAL, Color.GRAY));
            subtitle.setSpacingAfter(20);
            document.add(subtitle);

            // Patient Info section
            document.add(new Paragraph("Patient Information", sectionFont));
            document.add(spacer(6));

            addField(document, "Name:", nullSafe(user.getName()), labelFont, valueFont);
            addField(document, "Email:", nullSafe(user.getEmail()), labelFont, valueFont);
            if (user.getAge() != null) {
                addField(document, "Age:", String.valueOf(user.getAge()), labelFont, valueFont);
            }
            if (user.getBloodGroup() != null && !user.getBloodGroup().isEmpty()) {
                addField(document, "Blood Group:", user.getBloodGroup(), labelFont, valueFont);
            }
            if (user.getAllergies() != null && !user.getAllergies().isEmpty()) {
                addField(document, "Known Allergies:", user.getAllergies(), labelFont, valueFont);
            }
            if (user.getMedicalHistory() != null && !user.getMedicalHistory().isEmpty()) {
                addField(document, "Medical History:", user.getMedicalHistory(), labelFont, valueFont);
            }

            document.add(spacer(16));

            // Consultation details
            document.add(new Paragraph("Consultation Details", sectionFont));
            document.add(spacer(6));

            String dateStr = session.getCreatedAt() != null
                    ? session.getCreatedAt().format(DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a"))
                    : "N/A";
            addField(document, "Date:", dateStr, labelFont, valueFont);
            addField(document, "Session ID:", String.valueOf(session.getId()), labelFont, valueFont);

            String severity = session.getSeverity() != null ? session.getSeverity() : "N/A";
            Color severityColor = "HIGH".equalsIgnoreCase(severity) ? new Color(255, 92, 124)
                    : "MEDIUM".equalsIgnoreCase(severity) ? new Color(230, 160, 30)
                    : new Color(0, 150, 100);
            Paragraph severityPara = new Paragraph();
            severityPara.add(new Chunk("Severity: ", labelFont));
            severityPara.add(new Chunk(severity, new Font(Font.HELVETICA, 11, Font.BOLD, severityColor)));
            severityPara.setSpacingAfter(6);
            document.add(severityPara);

            document.add(spacer(10));

            // Diagnosis
            document.add(new Paragraph("AI Diagnosis & Summary", sectionFont));
            document.add(spacer(6));

            String diagnosisText = session.getDiagnosis() != null && !session.getDiagnosis().isEmpty()
                    ? session.getDiagnosis()
                    : "No diagnosis summary available.";
            Paragraph diagnosisPara = new Paragraph(diagnosisText, valueFont);
            diagnosisPara.setSpacingAfter(20);
            document.add(diagnosisPara);

            // Disclaimer
            document.add(spacer(10));
            Paragraph disclaimer = new Paragraph(
                    "Disclaimer: This report was generated by an AI-powered virtual assistant and is intended " +
                    "for informational purposes only. It is not a substitute for professional medical diagnosis, " +
                    "advice, or treatment. Please consult a qualified healthcare provider for any medical concerns.",
                    disclaimerFont);
            document.add(disclaimer);

            document.close();
            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF report: " + e.getMessage(), e);
        }
    }

    private void addField(Document document, String label, String value, Font labelFont, Font valueFont) throws DocumentException {
        Paragraph p = new Paragraph();
        p.add(new Chunk(label + " ", labelFont));
        p.add(new Chunk(value, valueFont));
        p.setSpacingAfter(4);
        document.add(p);
    }

    private Paragraph spacer(float size) {
        Paragraph p = new Paragraph(" ");
        p.setSpacingAfter(size);
        return p;
    }

    private String nullSafe(String value) {
        return value != null ? value : "N/A";
    }
}